# Example Docker Compose file for Fly.io deployment
# All services will be deployed as containers in a single machine
version: "3"
services:
  app:
    image: nginx:alpine
    ports:
      - "8080:80"
    environment:
      APP_ENV: production
      PORT: 80
    restart: always
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: secret
  cache:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: ""