version: "3"
services:
  app:
    image: myapp:latest
    ports:
      - "8080:8080"
    environment:
      APP_ENV: production
      PORT: 8080
    command: ["./start.sh"]
    restart: always
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: secret
  cache:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: ""